name: Continuous integration

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test (and build)
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean installation
        run: npm ci

      - name: Run test suite
        run: npm test

      - name: Build (if present)
        run: npm run build --if-present

      - name: CodeQL initialization
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v2

    strategy:
      matrix:
        node-version: [16.19.x, 18.12.x, 19.3.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
